import type { Metadata } from 'next'

import { LegalContent } from '@/components/public/LegalContent'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'How Vanguardia Financial collects, uses, and protects your account information.',
  alternates: { canonical: '/privacy' },
}

export default function PrivacyPage() {
  return (
    <LegalContent
      title="Privacy Policy"
      effectiveDate="September 4, 2026"
      intro={
        <p>
          This Privacy Policy explains what information Vanguardia Financial (&ldquo;we,&rdquo; &ldquo;us&rdquo;) collects when you use
          the platform, how we use it, and the choices you have. It applies to the Vanguardia Financial web application and does not
          cover third-party sites we may link to.
        </p>
      }
      sections={[
        {
          id: 'information-we-collect',
          heading: '1. Information We Collect',
          body: (
            <>
              <p>We collect information you provide directly and information generated by your use of the platform:</p>
              <ul className="list-disc space-y-1.5 pl-5">
                <li><span className="font-medium text-navy-800">Account information</span> — full name, email address, username, and a securely hashed password (we never store your password in plain text).</li>
                <li><span className="font-medium text-navy-800">Trading activity</span> — orders, positions, watchlist entries, and ledger transactions you generate within the trading environment.</li>
                <li><span className="font-medium text-navy-800">Security & session data</span> — login timestamps, approximate IP-derived location, device/browser identifiers, and active session tokens, used to protect your account.</li>
                <li><span className="font-medium text-navy-800">Technical data</span> — standard request logs (timestamps, endpoint, response status) collected by our infrastructure for reliability and abuse prevention.</li>
              </ul>
            </>
          ),
        },
        {
          id: 'how-we-use-it',
          heading: '2. How We Use This Information',
          body: (
            <>
              <p>We use the information above to:</p>
              <ul className="list-disc space-y-1.5 pl-5">
                <li>Operate your account and the trading, portfolio, and wallet features;</li>
                <li>Authenticate you, keep your account secure, and detect suspicious login activity;</li>
                <li>Maintain the audit trail required for our immutable transaction ledger;</li>
                <li>Respond to support requests and communicate important account or security notices; and</li>
                <li>Improve the reliability and usability of the platform.</li>
              </ul>
              <p>We do not sell your personal information.</p>
            </>
          ),
        },
        {
          id: 'cookies',
          heading: '3. Cookies & Local Storage',
          body: (
            <p>
              We use browser storage (such as local storage and session tokens) to keep you signed in and to remember basic
              preferences like display theme. We do not use third-party advertising trackers.
            </p>
          ),
        },
        {
          id: 'data-security',
          heading: '4. Data Security',
          body: (
            <p>
              Passwords are hashed using industry-standard algorithms and are never stored or transmitted in plain text. Access to
              the platform is protected with short-lived JSON Web Tokens and rotating refresh tokens. Administrative access to user
              data is role-restricted and every sensitive administrative action is recorded in an internal audit log. No method of
              transmission or storage is 100% secure, and we cannot guarantee absolute security.
            </p>
          ),
        },
        {
          id: 'data-retention',
          heading: '5. Data Retention',
          body: (
            <p>
              We retain account and ledger data for as long as your account remains active, and for a reasonable period afterward as
              needed to comply with legal obligations, resolve disputes, and enforce our agreements. You may request deletion of your
              account by contacting us, subject to any retention we are legally required to maintain.
            </p>
          ),
        },
        {
          id: 'your-rights',
          heading: '6. Your Rights & Choices',
          body: (
            <p>
              Depending on your location, you may have the right to access, correct, export, or delete the personal information we
              hold about you. You can review and update most of your account information directly from Profile settings, and manage
              active sessions and devices from Security settings. For anything else, contact us using the details below.
            </p>
          ),
        },
        {
          id: 'childrens-privacy',
          heading: "7. Children's Privacy",
          body: (
            <p>
              The Platform is not directed to individuals under 18, and we do not knowingly collect personal information from
              children. If you believe a child has provided us with personal information, please contact us so we can remove it.
            </p>
          ),
        },
        {
          id: 'changes',
          heading: '8. Changes to This Policy',
          body: (
            <p>
              We may update this Privacy Policy from time to time. We will update the &ldquo;Effective&rdquo; date above when we do,
              and material changes will be communicated through the Platform.
            </p>
          ),
        },
        {
          id: 'contact',
          heading: '9. Contact',
          body: (
            <>
              <p>
                Questions about this Privacy Policy can be directed to Vanguardia Financial:
              </p>
              <ul className="mt-3 space-y-1 text-sm">
                <li>Address: 1350 6th Avenue, New York, NY 10019</li>
                <li>Phone: +1-934-202-5711 or +1-208-974-2356</li>
                <li>Email: contact@vanguardiafinancial.com</li>
                <li>Website: vanguardiafinancial.com</li>
              </ul>
            </>
          ),
        },
      ]}
    />
  )
}
