"""Add account_type to accounts, positions, and orders

Revision ID: 3d5ac035bcc8
Revises: 08ec64e1f104
Create Date: 2026-09-06 21:26:52.874349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3d5ac035bcc8'
down_revision: Union[str, None] = '08ec64e1f104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add account_type columns as nullable first
    op.add_column('accounts', sa.Column('account_type', sa.Enum('demo', 'real', name='accounttype', native_enum=False, length=32), nullable=True))
    op.add_column('orders', sa.Column('account_type', sa.Enum('demo', 'real', name='accounttype', native_enum=False, length=32), nullable=True))
    op.add_column('positions', sa.Column('account_type', sa.Enum('demo', 'real', name='accounttype', native_enum=False, length=32), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE accounts SET account_type = 'demo' WHERE account_type IS NULL")
    op.execute("UPDATE orders SET account_type = 'demo' WHERE account_type IS NULL")
    op.execute("UPDATE positions SET account_type = 'demo' WHERE account_type IS NULL")

    # Now make columns NOT NULL
    op.alter_column('accounts', 'account_type', nullable=False)
    op.alter_column('orders', 'account_type', nullable=False)
    op.alter_column('positions', 'account_type', nullable=False)

    # Add indexes and constraints
    op.drop_constraint('uq_account_user_currency', 'accounts', type_='unique')
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_unique_constraint('uq_account_user_currency_type', 'accounts', ['user_id', 'currency', 'account_type'])
    op.create_index(op.f('ix_orders_account_type'), 'orders', ['account_type'], unique=False)
    op.create_index(op.f('ix_positions_account_type'), 'positions', ['account_type'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_account_type'), table_name='positions')
    op.drop_column('positions', 'account_type')
    op.drop_index(op.f('ix_orders_account_type'), table_name='orders')
    op.drop_column('orders', 'account_type')
    op.drop_constraint('uq_account_user_currency_type', 'accounts', type_='unique')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.create_unique_constraint('uq_account_user_currency', 'accounts', ['user_id', 'currency'])
    op.drop_column('accounts', 'account_type')
    # ### end Alembic commands ###
