"""Add deposit wallets and deposit tracking tables

Revision ID: 4a7938aec89f
Revises: 6d80cd8b4fe7
Create Date: 2026-09-06 12:15:37.909213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a7938aec89f'
down_revision: Union[str, None] = '6d80cd8b4fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_adjustments', 'adjustment_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('credit', 'debit', name='adjustmenttype', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('admin_positions', 'position_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('open', 'closed', name='positionstatus', native_enum=False, length=32),
               existing_nullable=False)
    op.drop_constraint('uq_assets_symbol', 'assets', type_='unique')
    op.drop_index('ix_assets_symbol', table_name='assets')
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.alter_column('audit_logs', 'actor_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('user', 'admin', 'system', name='auditactortype', native_enum=False, length=32),
               existing_nullable=False)
    op.drop_constraint('uq_market_prices_asset_id', 'market_prices', type_='unique')
    op.create_index(op.f('ix_market_prices_asset_id'), 'market_prices', ['asset_id'], unique=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('security', 'trade', 'system', 'admin', name='notificationtype', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('orders', 'side',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('buy', 'sell', name='orderside', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('orders', 'order_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('market', 'limit', 'stop_limit', name='ordertype', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'open', 'filled', 'partially_filled', 'cancelled', 'rejected', name='orderstatus', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('positions', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('open', 'closed', name='positionstatus', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('trades', 'side',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('buy', 'sell', name='orderside', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('transaction_ledger', 'transaction_type',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('TRADE_BUY', 'TRADE_SELL', 'POSITION_CLOSE', 'ADMIN_CREDIT', 'ADMIN_DEBIT', 'DEPOSIT', 'WITHDRAWAL', name='transactiontype', native_enum=False, length=32),
               existing_nullable=False)
    op.drop_index('ix_transaction_ledger_type', table_name='transaction_ledger')
    op.drop_constraint('uq_transaction_ledger_ref', 'transaction_ledger', type_='unique')
    op.create_index(op.f('ix_transaction_ledger_transaction_ref'), 'transaction_ledger', ['transaction_ref'], unique=True)
    op.create_index(op.f('ix_transaction_ledger_transaction_type'), 'transaction_ledger', ['transaction_type'], unique=False)
    op.drop_constraint('uq_user_financial_settings_user', 'user_financial_settings', type_='unique')
    op.drop_index('ix_user_financial_settings_user_id', table_name='user_financial_settings')
    op.create_index(op.f('ix_user_financial_settings_user_id'), 'user_financial_settings', ['user_id'], unique=True)
    op.drop_constraint('uq_user_sessions_jti', 'user_sessions', type_='unique')
    op.create_index(op.f('ix_user_sessions_refresh_token_jti'), 'user_sessions', ['refresh_token_jti'], unique=True)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('pending_verification', 'active', 'suspended', 'banned', name='userstatus', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('user', 'admin', 'super_admin', name='userrole', native_enum=False, length=32),
               existing_nullable=False)
    op.alter_column('users', 'risk_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('normal', 'watch', 'high_risk', name='riskstatus', native_enum=False, length=32),
               existing_nullable=False)
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_constraint('uq_users_username', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.alter_column('users', 'risk_status',
               existing_type=sa.Enum('normal', 'watch', 'high_risk', name='riskstatus', native_enum=False, length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('user', 'admin', 'super_admin', name='userrole', native_enum=False, length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.Enum('pending_verification', 'active', 'suspended', 'banned', name='userstatus', native_enum=False, length=32),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_sessions_refresh_token_jti'), table_name='user_sessions')
    op.create_unique_constraint('uq_user_sessions_jti', 'user_sessions', ['refresh_token_jti'])
    op.drop_index(op.f('ix_user_financial_settings_user_id'), table_name='user_financial_settings')
    op.create_index('ix_user_financial_settings_user_id', 'user_financial_settings', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_financial_settings_user', 'user_financial_settings', ['user_id'])
    op.drop_index(op.f('ix_transaction_ledger_transaction_type'), table_name='transaction_ledger')
    op.drop_index(op.f('ix_transaction_ledger_transaction_ref'), table_name='transaction_ledger')
    op.create_unique_constraint('uq_transaction_ledger_ref', 'transaction_ledger', ['transaction_ref'])
    op.create_index('ix_transaction_ledger_type', 'transaction_ledger', ['transaction_type'], unique=False)
    op.alter_column('transaction_ledger', 'transaction_type',
               existing_type=sa.Enum('TRADE_BUY', 'TRADE_SELL', 'POSITION_CLOSE', 'ADMIN_CREDIT', 'ADMIN_DEBIT', 'DEPOSIT', 'WITHDRAWAL', name='transactiontype', native_enum=False, length=32),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('trades', 'side',
               existing_type=sa.Enum('buy', 'sell', name='orderside', native_enum=False, length=32),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('positions', 'status',
               existing_type=sa.Enum('open', 'closed', name='positionstatus', native_enum=False, length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('pending', 'open', 'filled', 'partially_filled', 'cancelled', 'rejected', name='orderstatus', native_enum=False, length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'order_type',
               existing_type=sa.Enum('market', 'limit', 'stop_limit', name='ordertype', native_enum=False, length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('orders', 'side',
               existing_type=sa.Enum('buy', 'sell', name='orderside', native_enum=False, length=32),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.Enum('security', 'trade', 'system', 'admin', name='notificationtype', native_enum=False, length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_market_prices_asset_id'), table_name='market_prices')
    op.create_unique_constraint('uq_market_prices_asset_id', 'market_prices', ['asset_id'])
    op.alter_column('audit_logs', 'actor_type',
               existing_type=sa.Enum('user', 'admin', 'system', name='auditactortype', native_enum=False, length=32),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.create_index('ix_assets_symbol', 'assets', ['symbol'], unique=False)
    op.create_unique_constraint('uq_assets_symbol', 'assets', ['symbol'])
    op.alter_column('admin_positions', 'position_status',
               existing_type=sa.Enum('open', 'closed', name='positionstatus', native_enum=False, length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('admin_adjustments', 'adjustment_type',
               existing_type=sa.Enum('credit', 'debit', name='adjustmenttype', native_enum=False, length=32),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
