"""Add account_type to admin_positions

Revision ID: 719894fc6cca
Revises: 72afe59b05ff
Create Date: 2026-09-07 03:55:38.368238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '719894fc6cca'
down_revision: Union[str, None] = '72afe59b05ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_positions', sa.Column('account_type', sa.Enum('demo', 'real', name='accounttype', native_enum=False, length=32), nullable=False))
    op.create_index(op.f('ix_admin_positions_account_type'), 'admin_positions', ['account_type'], unique=False)
    op.drop_constraint('uq_users_display_id', 'users', type_='unique')
    op.drop_index('ix_users_display_id', table_name='users')
    op.create_index(op.f('ix_users_display_id'), 'users', ['display_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_display_id'), table_name='users')
    op.create_index('ix_users_display_id', 'users', ['display_id'], unique=False)
    op.create_unique_constraint('uq_users_display_id', 'users', ['display_id'])
    op.drop_index(op.f('ix_admin_positions_account_type'), table_name='admin_positions')
    op.drop_column('admin_positions', 'account_type')
    # ### end Alembic commands ###
