"""Add user_paid workflow fields to deposits

Revision ID: cdf379ef5c0f
Revises: 719894fc6cca
Create Date: 2026-09-07 05:03:44.093225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cdf379ef5c0f'
down_revision: Union[str, None] = '719894fc6cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposits', sa.Column('user_marked_paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deposits', sa.Column('admin_confirmed_by', sa.UUID(), nullable=True))
    op.add_column('deposits', sa.Column('admin_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'deposits', 'users', ['admin_confirmed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deposits', type_='foreignkey')
    op.drop_column('deposits', 'admin_confirmed_at')
    op.drop_column('deposits', 'admin_confirmed_by')
    op.drop_column('deposits', 'user_marked_paid_at')
    # ### end Alembic commands ###
